# Generated by Django 2.0.4 on 2018-06-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('epu_score', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpuIndexScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('number_of_articles', models.IntegerField()),
                ('number_of_papers', models.IntegerField()),
                ('epu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalsScraped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spider_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordsPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wordsperday',
            unique_together={('word', 'date')},
        ),
        migrations.AddField(
            model_name='journalsscraped',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epu_index.NewsJournal'),
        ),
        migrations.AddField(
            model_name='article',
            name='news_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epu_index.NewsJournal'),
        ),
        migrations.AlterUniqueTogether(
            name='journalsscraped',
            unique_together={('journal', 'date')},
        ),
    ]
